### ISSUE TITLE
 anonymous access 

### ISSUE THREAD

**Issue by 89z** [jlobos/instagram-stories#19]
Is it possible to get post information, from a public page such as this:

https://www.instagram.com/p/CT-cnxGhvvO/

without login?

**Comment by dmkonstantinov** [comment]
The short answer is no, it isn't possible. 

More long oneInstagram has some kind of bot detection and when you trying to grab JSON from page https://www.instagram.com/p/CT-cnxGhvvO/?__a=1 it redicts you to login page. You may have some experiments with setting `user-agent` header to something like real browser, but i recommend to you just use credentials, it is the most stable way. 

Cheers.

**Comment by konstantinov** [comment]
Hey, @89z 

The short answer is no, it isn't possible.

More long oneInstagram has some kind of bot detection and when you trying to grab JSON from page https://www.instagram.com/p/CT-cnxGhvvO/?__a=1 it redicts you to login page. You may have some experiments with setting user-agent header to something like real browser, but i recommend to you just use credentials, it is the most stable way.

Cheers.

**Comment by 89z** [comment]
@konstantinov every single JSON API I have seen so far does have (severe) bot detection, where even something like 16 requests, one per second, will trigger it. However I dont agree with your assessment that its not possible. I found the embed pages dont seem to have bot protection:

https://www.instagram.com/p/CT-cnxGhvvO/embed/

granted, the JSON is embedded in HTML, but its something. I will keep looking.

**Comment by dmkonstantinov** [comment]
@89z oh may be i put it wrong, i mean there is no way in this package. Of course you can grab the same JSON from the public html at the link your provided. But you should know both ways (my and your) is not an official API so in any time you have a risk to get a block, and caus of UNOFFICIAL way to grabbing bot protection is quite stronger than regular APIs has

**Comment by konstantinov** [comment]
@89z oh may be i put it wrong, i mean there is no way in this package. Of course you can grab the same JSON from the public html at the link your provided. But you should know both ways (my and your) is not an official API so in any time you have a risk to get a block, and caus of UNOFFICIAL way to grabbing bot protection is quite stronger than regular APIs has
