### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by timmykill** [jlobos/instagram-stories#2]
Hi, I'm trying to automate the download of some instagram stories but I still can't get from the reel_media json to the actual media.
What kind of request do I have to make? Is it even possible?

**Comment by jlobos** [comment]
@timmykill you get the stories?

This function get the stories:
```js
// Get stories of Instagram
// id:        account id for get stories
// userid:    me id
// sessionid: value of cookies from Instagram
getStories({ id: 25025320, userid: 1284161654, sessionid: '' }).then(stories => {
  console.log(stories)
})
```
