### ISSUE TITLE
Response Error In Get Stories

### ISSUE THREAD

**Issue by Thilina-B** [jlobos/instagram-stories#21]
This error occurs when calling the "getStories" function after the new version update.
"UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined"

**Comment by konstantinov** [comment]
Hi! Thank you for your report. New version released `1.2.1`. Let me know if you will face this problem again.

**Comment by Thilina-B** [comment]
It's working exceptionally well. Thanks in advance
