### ISSUE TITLE
[Request] Highlight_Stories

### ISSUE THREAD

**Issue by optionsx** [jlobos/instagram-stories#22]
could you do us a favor and add it, thanks bro!

getUserHighlightsWithSession(userID, sessionID) {
		if (typeof userID !== 'string' || typeof sessionID !== 'string') {
			throw new TypeError(`Expected a string, got ${typeof userID !== 'string' ? typeof userID : typeof sessionID}`);
		}

		return axios({
			method: 'GET',
			url: `https://i.instagram.com/api/v1/highlights/${userID}/highlights_tray/`,
			headers: {
				'Cookie': `sessionid=${sessionID}`,
				'User-Agent': 'Instagram 9.5.1 (iPhone9,2; iOS 10_0_2; en_US; en-US; scale=2.61; 1080x1920) AppleWebKit/420+'
			}
		})
		.then((response) => response)
		.catch((error) => error);
	}

**Comment by konstantinov** [comment]
@optionsx Hey! Thank you for your request. I will prepare new release with this code soon.

**Comment by konstantinov** [comment]
@optionsx Hey! Thank you for your patience! Version 1.2.2 is released on npm and available for update.
