### ISSUE TITLE
Library is not working

### ISSUE THREAD

**Issue by TyphousCrane654** [jlobos/instagram-stories#25]
This library is using Instagram API v1 which is deprecated. Therefore, the library is not working.
In addition, there are multiple errors in the example code.

**Comment by konstantinov** [comment]
@TyphousCrane654 hi there! Thank you for report. I see problems with methods `getUserHighlights` and `getMediaByLocation`. I will investigate situation and fix asap. If you have problems with other methods, please, provide more information about your case. Cheers.

**Comment by konstantinov** [comment]
@TyphousCrane654 by the way why did you mention `v1` as deprecated? I see request to `https://i.instagram.com/api/v1/feed/reels_tray/` on official instagram website.

**Comment by konstantinov** [comment]
I've checked errors in tests and can mention only change in data structure on instagram side. I pushed fixed tests, but don't feel it is enough to publish new version. Feel free to share your code faced issues

**Comment by konstantinov** [comment]
`getUserByUsername` fixed in new version. Unfortunately, `getMediaByCode` is not working for now.
